blank_issues_enabled: false
contact_links:
  - name: gustavosalvini-astro-blog Discussions
    url: https://github.com/guspatagonico/gustavosalvini-astro-blog/discussions
    about: Please ask and answer questions here.
